### ISSUE TITLE
Repositioning of ComponentView does not work as expected

### ISSUE THREAD

**Issue by jridderbusch** [tudo-aqua/bgw#199] opened 2021-11-28 16:25 UTC
**Describe the bug**
When using ComponentView.reposition(x, y) e.g. of a CardStack inside GridPane, with the value of x and/or y beeing 0, the position is not set correctly.
After some investigation this seems to be related to the properties "posX" and "posY" of aforementioned CardStack beeing 0 despite its position showing correctly. Which leads to the problem that when it is to be repositioned to (0, 0), these values will not be set since the are the same as the old ones.

**To Reproduce**
1. Create a GridPane
2. Create a CardStack inside the GridPane
3. Reposition the CardStack with values != 0
4. Reposition the CardStack with values (0, 0)

**Expected behavior**
The position properties of the CardStack are changed according to the passed values, so that a later repositioning to (0, 0) is possible.

Please complete the following information):
 - OS: Windows 10
 - Java version: Kotlin SDK 1.6.0-release-798

**Comment by fabiankluempers** [comment] 2021-12-03 23:41
Probably related to #161 .

**Comment by dominikmaeckel** [comment] 2022-03-06 13:41
Duplicate of #161.

**Closed by dominikmaeckel** 2022-03-06 13:41 UTC
Labels: bug
